config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  namespace :api do
    namespace :v1 do
        resources :users
        resources :lessons
        resources :spots
    end
  end

get '*path', to: 'pages#home', via: :all

  

end

app/models/spot.rb
class Spot < ApplicationRecord
    belongs_to :user, optional: true
    has_many :lessons, dependent: :destroy
end

app/controllers/api/v1/spots_controller.rb
module Api
  module V1
    class SpotsController < ApplicationController
      def index
        spots = Spot.all
        
        render json: SpotSerializer.new(spots, options).serialized_json
      end
      
      def show
        spot = Spot.find_by_id(params[:id])
        render json: SpotSerializer.new(spot, options).serialized_json
      end

      def create
        spot = Spot.new(spot_params)
        if spot.save
          render json: SpotSerializer.new(spot).serialized_json
        else
          render json: {error: spot.errors.messages}, status: 422
        end
      end    

      def destroy
        spot = Spot.find_by_id(params[:id])
        
        if spot.destroy
          head :no_content
        else
          render json: {error: spot.errors.messages}, status: 422
        end
      end
      
          
      def update
        spot = Spot.find_by_id(params[:id])
        
        if spot.update(spot_params)
          render json: SpotSerializer.new(spot, options).serialized_json
        else
          render json: {error: spot.errors.messages}, status: 422
        end
      
      end
      
      private
      def spot_params
        params.require(:spot).permit(:start_date, :end_date, :weekday, :time, :spot_index_number, :user_id, :lesson_amount)
      end

      def options
        @options ||= {include: %i[lessons]}
      end
    end
  end
end

app/helpers/spots_helper.rb
module SpotsHelper
end

app/views/spots/_edit_form.erb
<%= form_with(model: model ) do |form|%>

    
        <%= form.label :period %> 
        <%= form.select :period, options_for_select(['March', 'April'])%>
        <br/>
 
    
        
    
        <%= form.label :weekday %>
        <%= form.select :weekday, weekday_options_for_select( index_as_value: false, day_format: :day_names),  class:'form-control' %>
        <br/>
        

    
        <%= form.label :time %>
        <%= form.select :time, options_for_select([18, 20])%>
        <br/>

        
        <%= form.label :spot_index_number %>
        <%= form.number_field :spot_index_number%>
        <br/>
        
    
       
        
    
        <%= form.label :lesson_amount %>
        <%= form.number_field :lesson_amount,  class:'form-control'%>
        <br/>

        <hr/>

        <%= form.label :user_id %>
        <%= form.select :user_id, @users.map { |user| [user.full_name, user.id]},  class:'form-control' %>
        <br/>

    
    <%= form.submit "Create" %>
   
    
   
<%= link_to 'Cancel', spots_path, class: 'btn btn-secondary' %>

<% end %>

app/views/spots/_inline_edit.html.erb
<% frame_id = dom_id(model, "#{attribute}_turbo_frame")%>
<%= form_with model: model, data: {turbo_frame: frame_id} do %>
  <%= turbo_frame_tag frame_id do %>
    <%= yield %>
    <span><%= link_to 'Edit', edit_polymorphic_path(model)%></span>
  <% end %>
<%end %>

app/views/spots/_inline_fields.html.erb
  <% frame_id = dom_id(form.object, "#{attribute}_turbo_frame")%>
    <%= turbo_frame_tag frame_id do %>
    <%= yield %>
    <%= form.button 'Save'%>
    <% end %>

app/views/spots/_new_form.erb
<%= form_with(model: model ) do |form|%>
    <div class='form-group'>
        <%= form.label :period %>
        <%= form.text_field :period%>
    </div>

    <div class='form-group'>
        <%= form.label :weekday %>
        <%= form.select :weekday, weekday_options_for_select( index_as_value: false, day_format: :day_names), class: 'form-control' %>
        
    </div>

    <div class='form-group'>
        <%= form.label :time %>
        <%= form.number_field :time, class: 'form-control'%>
    </div>

    <div class='form-group'>
        <%= form.label :spot_index_number %>
        <%= form.number_field :spot_index_number, class: 'form-control'%>
    </div>

    <div class='form-group'>
        <%= form.label :user_id %>
        <%= form.select :user_id, @users.map { |user| [user.full_name, user.id]} %>
    </div>

    <div class='form-group'>
        <%= form.label :lesson_amount %>
        <%= form.number_field :lesson_amount, class: 'form-control'%>
    </div>

    <div class="actions">
    <%= form.submit "Create" %>
    </div>
</div>   
<%= link_to 'Cancel', spots_path, class: 'btn btn-secondary' %>

<% end %>

app/views/spots/edit.html.erb
<%= form_with(model: @spot,   url: spot_path, ) do |form|%>
<tr>
   
  
   
        <td><%= form.text_field :period%></td>
        
        
        <td><%= form.select :weekday, weekday_options_for_select( index_as_value: false, day_format: :day_names), class: 'form-control' %> </td>
        
        
            
        <td><%= form.number_field :time%></td>
        
        
            
        <td><%= form.number_field :spot_index_number%></td>
        <td>
            <% frame_id = dom_id(@spot)%>
            <%= turbo_frame_tag frame_id do %>
                <%= form.select :user_id, @users.map { |user| [user.full_name, user.id]} %>
            <% end %>
        </td>
        
        <td><%= form.number_field :lesson_amount%></td>
        
        
        <td><%= form.button 'Save'%></td>
    
     
</tr>
<% end%>
<br />
<br />

<%= link_to 'Cancel', spots_path, class: 'btn btn-secondary' %>

app/views/spots/index.html.erb
<div class='overview-menu'>
  <div class='menu-area'>
  <h2>Filters</h2>
    <%= form_tag(spots_path, method: "get", remote: true) do %>


      <%= select_tag "start_date", options_for_select(Spot.all.map {|date| date.start_date}.uniq), class:'custom-select'%>    
      <br/> 
      <%= select_tag "weekday", options_for_select(['Select weekday', 
      'Monday', 
      'Tuesday']), class:'custom-select'%>
      <br/>
      <%= select_tag 'time', options_for_select(['Select time', 18, 20]) %>

      <%= submit_tag "Search", class:'btn btn-dark', id:'search_submit'%>
                  
    <% end %>
  </div>    

  <div class = 'menu-area'>
    <h2>New Spot</h2>
      
    <%= render 'new_form', model: @spot%>
  </div>
</div>
</div>
<br/>
<div class='overview-table'>
 <table class='table'>  
    <thead>    
      <th>Starting date</th>
      <th>End date</th>
      <th>Weekday</th>
      <th>Time</th>
      <th>Index</th>
      <th>Student</th>
      <th>Lesson count</th>
    </div>
   </thead>
   <tbody>

<% @spots.each do |spot|%>


  <tr> <% frame_id = dom_id(spot )%>
  <%= form_with model: spot, data: {turbo_frame: frame_id} do %>
   
      <td> <%= spot.start_date%></td>
      <td> <%= spot.end_date%></td>
      <td> <%=spot.weekday%></td>
      <td> <%= spot.time %></td>
      <td> <%= spot.spot_index_number %></td> 
     <td> 
     
      <%= turbo_frame_tag frame_id do %>
         <%= spot.user.full_name %><%= link_to 'Edit', edit_spot_path(spot)%>
      <% end %></td> 
      <td> <%= spot.lesson_amount %></td>
  
      
      <td><%= link_to 'Show', spot_path(spot)%> <%= link_to 'Edit', edit_spot_path(spot)%> <%= button_to 'Delete', spot,  :method => :delete %></td>
  
      
   
   
  <%end %> 
  </tr>
<% end %>
</tbody>
</table>
</div>
    
 

app/views/spots/new.html.erb
<%= render 'new_form', model: @spot %>

app/views/spots/show.html.erb
<div>Starts: <%=@spot.start_date%></div>
<div>Ends: <%=@spot.end_date%></div>

<div>Weekday: <%=@spot.weekday%></div>
<div>Time: <%=@spot.time%></div>
<div>Student: <%=@spot.user.full_name%></div>
<div>Lesson count: <%=@spot.lesson_amount%></div>



<table class="table">
  <thead>
    <tr>
    
      <th scope="col">Date</th>
      <th scope="col">Timeslot</th>
      
    </tr>
  </thead>
  <tbody>
  
    <% @lessons.each do | lesson | %>
    <tr>
      <th scope="row"><%= lesson.date %></th>
      <td><%= lesson.timeslot %></td>
      <td><%= link_to 'Show', lesson_path(lesson)%> <%= link_to 'Edit', edit_lesson_path(lesson)%></td>

    </tr>
    <% end %>
  </tbody>
</table>