config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  get '/dashboard', to: 'pages#dashboard'
  
  devise_for :users, controllers: {registrations: 'users/registrations', sessions: 'users/sessions'}
  namespace :api do
    namespace :v1 do
        resources :users
        resources :lessons
        resources :spots
    end
  end

get '*path', to: 'pages#home', via: :all

  

end

app/models/lesson.rb
class Lesson < ApplicationRecord
  
    belongs_to :spot
end

app/controllers/api/v1/lessons_controller.rb
module Api
  module V1
    class LessonsController < ApplicationController
      def index
        lessons = Lesson.all
        
        render json: LessonSerializer.new(lessons ).serialized_json
      end
      
      def show
        lesson = Lesson.find_by_id(params[:id])
        render json: LessonSerializer.new(lesson ).serialized_json
      end

      def create
        lesson = Lesson.new(lesson_params)
        if lesson.save
          render json: LessonSerializer.new(lesson).serialized_json
        else
          render json: {error: lesson.errors.messages}, status: 422
        end
      end    

      def destroy
        lesson = Lesson.find_by_id(params[:id])
        
        if lesson.destroy
          head :no_content
        else
          render json: {error: lesson.errors.messages}, status: 422
        end
      end
      
          
      def update
        lesson = Lesson.find_by_id(params[:id])
        
        if lesson.update(lesson_params)
          render json: LessonSerializer.new(lesson, ).serialized_json
        else
          render json: {error: lesson.errors.messages}, status: 422
        end
      
      end
      
      private
      def lesson_params
        params.require(:lesson).permit(:date, :timeslot)
      end

     
    end
  end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/edit.html.erb
<%= form_for(@lesson,   url: lesson_path, ) do |form|%>
    <div class='form-group'>
    <%= form.label :date %>
    <%= form.text_field :date, class: 'form-control'%>
    </div>
    
    <div class='form-group'>
    <%= form.label :timeslot %>
    <%= form.number_field :timeslot, class: 'form-control'%>
    </div>
   
    <div class='form-group'>
    <%= form.label :spot_id %>
    <%= form.number_field :spot_id, class: 'form-control'%>
    </div>
     <div class="actions">
    <%= form.submit "Update" %>
    </div>
</div>   
<%= link_to 'Cancel', lessons_path, class: 'btn btn-secondary' %>

<% end %>

app/views/lessons/index.html.erb
<table class="table">
  <thead>
    <tr>
      <th scope="col">Spot Index</th>
      <th scope="col">Weekday</th>
      <th scope="col">Time</th>
      <th scope="col">Date</th>
      <th scope="col">Student</th>
     
      
    </tr>
  </thead>
  <tbody>
    <% @lessons.each do | lesson | %>
    <tr>
     
      <td><%= lesson.spot.spot_index_number %></td>
      <td><%= lesson.spot.weekday %></td>
      <td><%= lesson.timeslot %></td>
       <td><%= lesson.date %></td>
      <td><%= lesson.spot.user.full_name %></td>
      <td><%= link_to 'Show', lesson_path(lesson)%> <%= link_to 'Edit', edit_lesson_path(lesson)%></td>
</div>
    </tr>
    <% end %>
  </tbody>
</table>